version: '3'

# 指定ip容器内部相互访问
networks:
  standalone_my_net:
    external: true

services:
  # nacos-server:
  # Nacos2.0版本相比1.X新增了gRPC的通信方式，因此需要增加2个端口。新增端口是在配置的主端口(server.port)基础上，进行一定偏移量自动生成，所以开放的端口如果改动必须按照规定改动，否则会出现连接失败的问题
  # 链接：
  nacos-server-a:
    image: nacos/nacos-server
    container_name: nacos-server-a
    restart: on-failure
    env_file:
      - ./env/nacos-ip.env
    volumes:
      - ./nacos-server-a/logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    networks:
      standalone_my_net:
        ipv4_address: 172.30.0.61

  nacos-server-b:
    image: nacos/nacos-server
    container_name: nacos-server-b
    restart: on-failure
    env_file:
      - ./env/nacos-ip.env
    volumes:
      - ./nacos-server-b/logs/:/home/nacos/logs
    ports:
      - "8858:8848"
      - "9858:9848"
      - "9859:9849"
    networks:
      standalone_my_net:
        ipv4_address: 172.30.0.62

  nacos-server-c:
    image: nacos/nacos-server
    container_name: nacos-server-c
    restart: on-failure
    env_file:
      - ./env/nacos-ip.env
    volumes:
      - ./nacos-server-c/logs/:/home/nacos/logs
    ports:
      - "8868:8848"
      - "9868:9848"
      - "9869:9849"
    networks:
      standalone_my_net:
        ipv4_address: 172.30.0.63
