version: '3'

# 指定ip容器内部相互访问
networks:
  standalone_my_net:
    external: true

services:
  # nacos-server:
  # Nacos2.0版本相比1.X新增了gRPC的通信方式，因此需要增加2个端口。新增端口是在配置的主端口(server.port)基础上，进行一定偏移量自动生成，所以开放的端口如果改动必须按照规定改动，否则会出现连接失败的问题
  # 链接：
  nacos-server-a:
    image: nacos/nacos-server
    container_name: nacos-server-a
    restart: always
    external_links: # 连接本compose文件以外的container
      - mysql
    environment:
      TZ: Asia/Shanghai
      PREFER_HOST_MODE: ip
      MODE: cluster
      NACOS_SERVERS: nacos-server-a:8848 nacos-server-b:8848 nacos-server-c:8848
      SPRING_DATASOURCE_PLATFORM: mysql
      # mysql信息配置
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: L0rfBGXhvrt9f7L8
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      # JVM参数
      JVM_XMS: 128m
      JVM_XMX: 128m
      JVM_XMN: 128m
    volumes:
      - ./nacos-server-a/logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    networks:
      standalone_my_net:
        ipv4_address: 172.30.0.61

  nacos-server-b:
    image: nacos/nacos-server
    container_name: nacos-server-b
    restart: always
    external_links: # 连接本compose文件以外的container
      - mysql
    environment:
      TZ: Asia/Shanghai
      PREFER_HOST_MODE: ip
      MODE: cluster
      NACOS_SERVERS: nacos-server-a:8848 nacos-server-b:8848 nacos-server-c:8848
      SPRING_DATASOURCE_PLATFORM: mysql
      # mysql信息配置
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: L0rfBGXhvrt9f7L8
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      # JVM参数
      JVM_XMS: 128m
      JVM_XMX: 128m
      JVM_XMN: 128m
    volumes:
      - ./nacos-server-b/logs/:/home/nacos/logs
    ports:
      - "8858:8848"
      - "9858:9848"
      - "9859:9849"
    networks:
      standalone_my_net:
        ipv4_address: 172.30.0.62

  nacos-server-c:
    image: nacos/nacos-server
    container_name: nacos-server-c
    restart: always
    external_links: # 连接本compose文件以外的container
      - mysql
    environment:
      TZ: Asia/Shanghai
      PREFER_HOST_MODE: ip
      MODE: cluster
      NACOS_SERVERS: nacos-server-a:8848 nacos-server-b:8848 nacos-server-c:8848
      SPRING_DATASOURCE_PLATFORM: mysql
      # mysql信息配置
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: L0rfBGXhvrt9f7L8
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      # JVM参数
      JVM_XMS: 128m
      JVM_XMX: 128m
      JVM_XMN: 128m
    volumes:
      - ./nacos-server-c/logs/:/home/nacos/logs
    ports:
      - "8868:8848"
      - "9868:9848"
      - "9870:9849"
    networks:
      standalone_my_net:
        ipv4_address: 172.30.0.63
