version: "3"


networks:
  my_net:
    external: true

services:


  kafka-1:
    privileged: true
    image: bitnami/kafka:2.8.0
    container_name: kafka-1
    restart: always
    hostname: kafka-1
    ports:
      - '19092:9092'
    volumes:
      - ./kafka-1:/bitnami/kafka
    external_links:
      - cluster-zookeeper-1
      - cluster-zookeeper-2
      - cluster-zookeeper-3
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=cluster-zookeeper-1,cluster-zookeeper-2:2181,cluster-zookeeper-3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      my_net:
        ipv4_address: 172.30.0.52

  kafka-2:
    privileged: true
    image: bitnami/kafka:2.8.0
    container_name: kafka-2
    restart: always
    hostname: kafka-2
    ports:
      - '19093:9092'
    volumes:
      - ./kafka-2:/bitnami/kafka
    external_links:
      - cluster-zookeeper-1
      - cluster-zookeeper-2
      - cluster-zookeeper-3
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=cluster-zookeeper-1,cluster-zookeeper-2:2181,cluster-zookeeper-3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      my_net:
        ipv4_address: 172.30.0.53

  kafka-3:
    privileged: true
    image: bitnami/kafka:2.8.0
    container_name: kafka-3
    restart: always
    hostname: kafka-3
    ports:
      - '19094:9092'
    volumes:
      - ./kafka-3:/bitnami/kafka
    external_links:
      - cluster-zookeeper-1
      - cluster-zookeeper-2
      - cluster-zookeeper-3
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=cluster-zookeeper-1,cluster-zookeeper-2:2181,cluster-zookeeper-3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      my_net:
        ipv4_address: 172.30.0.54


  kafka-manager:
    image: sheepkiller/kafka-manager
    restart: always
    container_name: kafa-manager
    ports:
      - '9002:9000'
    links: # 连接本compose文件创建的container
      - kafka-1
      - kafka-2
      - kafka-3
    external_links: # 连接本compose文件以外的container
      - cluster-zookeeper-1
      - cluster-zookeeper-2
      - cluster-zookeeper-3
    environment:
      ZK_HOSTS: cluster-zookeeper-1:2181,cluster-zookeeper-2:2181,cluster-zookeeper-3:2181
      KAFKA_BROKERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    networks:
      my_net:
        ipv4_address: 172.30.0.55
