version: '3'

# 指定ip容器内部相互访问
networks:
  my_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

services:
  # --- MySQL
  mysql:
    image: mysql:8.0.27
    container_name: mysql
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # root 密码
      MYSQL_ROOT_PASSWORD: 12345678
      # 初始化数据库(后续的初始化sql会在这个库执行)
      # MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      # 数据挂载
      - ./mysql/data/:/var/lib/mysql/
      # 配置挂载
      - ./mysql/conf/:/etc/mysql/conf.d/
      # 日志
      - ./mysql/logs/:/logs
      # 初始化脚本
      - ./mysql/source:/docker-entrypoint-initdb.d
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_connections=2000
      --init-file /docker-entrypoint-initdb.d/tables_xxl_job.sql
    privileged: true
    restart: always
    networks:
      my_net:
        ipv4_address: 172.30.0.36

  # ---- Redis
  redis:
    image: redis:6.2.6
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      # 配置文件
      - ./redis/conf/redis.conf:/redis/config/redis.conf
      # 数据文件
      - ./redis/data/:/redis/data
    command: "redis-server /redis/config/redis.conf"
    privileged: true
    restart: always
    networks:
      my_net:
        ipv4_address: 172.30.0.48

  # --- MINIO
  minio:
    image: minio/minio:RELEASE.2022-04-16T04-26-02Z
    container_name: minio
    ports:
      # api 端口
      - "9000:9000"
      # 控制台端口
      - "9001:9001"
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # 管理后台用户名
      MINIO_ACCESS_KEY: minio
      # 管理后台密码，最小8个字符
      MINIO_SECRET_KEY: 12345678
      # https需要指定域名
      MINIO_SERVER_URL: ""
    volumes:
      # 映射当前目录下的data目录至容器内/data目录
      - ./minio/data:/data
      # 映射配置目录
      - ./minio/config:/root/.minio/
    command: server --address ':9000' --console-address ':9001' /data  # 指定容器中的目录 /data
    privileged: true
    restart: always
    networks:
      my_net:
        ipv4_address: 172.30.0.54

  # --- Zookeeper
  zookeeper:
    image: zookeeper:3.6.3
    container_name: zookeeper
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    privileged: true
    ports:
      - '2181:2181'
    networks:
      my_net:
        ipv4_address: 172.30.0.15

  # --- xxl-job-admin
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.3.0
    container_name: xxl-job-admin
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # 参数
      PARAMS: '--spring.datasource.url=jdbc:mysql://172.30.0.36:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=root --spring.datasource.password=12345678'
    volumes:
      # 配置文件
      - ./xxljob/applogs/:/data/applogs
    privileged: true
    restart: always
    ports:
      - '9091:8080'
    networks:
      my_net:
        ipv4_address: 172.30.0.92
