version: '3'


services:
  # --- spring-boot-monitor-admin
  spring-boot-monitor-admin:
    image: dev-envs/extend-spring-boot-monitor-admin:1.0
    container_name: spring-boot-monitor-admin
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      # 配置文件
      - ./monitor/logs/:/docker/monitor/logs
    privileged: true
    restart: always
    ports:
      - '9090:9090'
