version: '3'

networks:
  monitor:
    driver: bridge
    ipam:
      config:
        - subnet: 172.11.0.0/16

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    hostname: node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      monitor:
        ipv4_address: 172.11.0.2

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    hostname: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8088:8080"
    networks:
      monitor:
        ipv4_address: 172.11.0.3


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/node_down.yml:/etc/prometheus/node_down.yml
    ports:
      - "9090:9090"
    networks:
      monitor:
        ipv4_address: 172.11.0.4

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      monitor:
        ipv4_address: 172.11.0.5

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis_exporter
    hostname: redis_exporter
    restart: always
    ports:
      - "9121:9121"
    networks:
      monitor:
        ipv4_address: 172.11.0.6
    command:
      - '--redis.addr=redis://172.30.0.48:6379'

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql_exporter
    hostname: mysql_exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: root:12345678@(172.30.0.36:3306)
    ports:
      - "9104:9104"
    networks:
      monitor:
        ipv4_address: 172.11.0.7

