version: '3'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - '9999:9000'
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: always

